apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp-stateful
spec:
  serviceName: "webapp"
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:latest
          ports:
            - containerPort: 80
  volumeClaimTemplates:
    - metadata:
        name: webapp-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
